Traceback (most recent call last):
  File "C:\Dev\Code\iitm\tld\tds-proj-2-cloned\app\codes\task1\code0.py", line 27, in <module>
    df = pd.DataFrame(data[1:], columns=data[0])
                                        ~~~~^^^
IndexError: list index out of range
